### PR TITLE
Simplify http client contract

### LINKED ISSUE #125: Simplify http client contract
While the behaviour works well, I believe a much simpler contract will be a 1-arity function that accepts a keyword list with `:method`, `:url`, `:headers`, `:body` and passes remaining options through as adapter-specific. And it returns `{:ok, map} | {:error, exception}`. 

We'd configure it as simply: `http_client: &mod.fun/1`. If you'd want to adjust options, you'd: `http_client: {&mod.fun/1, options}`.

By default, we'd ship with Hackney-based adapter. To pass additional options to it, we'd do:

```elixir
http_client: {&Goth.__hackney__/1, options}
```

Here's roughly how the implementation would work (untested):

```elixir
  defmacrop ensure_hackney do
    if Code.ensure_loaded?(:hackney) do
      :ok
    else
      quote do
        unless Code.ensure_loaded?(:hackney) do
          raise "missing hackney dependency"
        end
      end
    end
  end

  def __hackney__(options) do
    ensure_hackney()

    {method, options} = Keyword.pop!(options, :method)
    {url, options} = Keyword.pop!(options, :url)
    {headers, options} = Keyword.pop!(options, :headers)
    {body, options} = Keyword.pop!(options, :body)
    options = [:with_body] ++ options

    case :hackney.request(method, url, headers, body, options) do
      {:ok, status, headers, body} ->
        {:ok, %{status: status, headers: headers, body: body}}

      {:error, reason} ->
        {:error, RuntimeError.exception(inspect(reason))}
    end
  end
```

### PR DESCRIPTION
**Pull request by aleDsz**
- Closes #125

### CODE REVIEW

File: lib/goth.ex [hunk 1]
```diff
@@ -33,9 +36,11 @@ defmodule Goth do
...
       `#{@refresh_before_minutes * 60}` (#{@refresh_before_minutes} minutes).
 
-    * `:http_client` - a `{module, opts}` tuple, where `module` implements the
-      `Goth.HTTPClient` behaviour and `opts` is a keywords list to initialize the client with.
-      Defaults to `{Goth.HTTPClient.Hackney, []}`.
+    * `:http_client` - a `{&fun/1, opts}` tuple or `&fun/1`, where `fun` is a
+      function reference with arity 1 and `opts` is a keywords list to initialize the client with.
+      The function will receive a keyword list with required fields: `:method`, `:url`, `:body` and
+      `:headers`, and `opts` merged into it, if available. And the function should return
+      `{:ok, map} | {:error, exception}`. Defaults to `{&Goth.__hackney__/1, []}`.
```
Comment (wojtekmach) [inline lib/goth.ex:43]: `Goth.__hackney__` is hidden so we shouldn't reference it from other docs. I think we could have a special value, atom `:hackney`, that means the built-adapter.

Here's a stab at this section:

```markdown
    * `:http_client` - a function that makes the HTTP request. Can be one of the following:

        * `fun` - same as `{fun, []}`

        * `{fun, opts}` - `fun` must be a 1-arity function that receives a keyword list with fields
          `:method`, `:url`, `:headers`, and `:body` along with any passed `opts`. The function must return
          `{:ok, %{status: status, headers: headers, body: body}}` or `{:error, exception}`.
          Example: `{&HTTPClient.request/1, connect_timeout: 5000}`.

          `fun` can also be an atom `:hackney` to use the built-in [Hackney](http://github.com/benoitc/hackney)-based
          client.

      Defaults to `{:hackney, []}`
```

wdyt?

File: lib/goth.ex [hunk 2]
```diff
@@ -77,12 +82,57 @@ defmodule Goth do
...
+
+              {:hackney, "~> 1.17"}
+
+          Or use a different HTTP client. See Goth for more information.
+          """)
+
+          raise "missing hackney dependency"
+        end
+
+        {:ok, _} = Application.ensure_all_started(:hackney)
```
Comment (wojtekmach) [inline lib/goth.ex:110]: 👍

File: test/goth_test.exs [hunk 3]
```diff
@@ -187,4 +257,36 @@ defmodule GothTest do
...
+    {:ok,
+     %{
+       status: 200,
+       body: ~s|{"access_token":"dummy","expires_in":3599,"token_type":"Bearer"}|
+     }}
+  end
+
+  defp validate_options(options) do
+    assert Keyword.keyword?(options)
+
```
Comment (wojtekmach) [inline test/goth_test.exs:286]: this is not needed since if we don't have a keyword, any of the assertions below would fail too.

```suggestion
```

File: lib/goth.ex [hunk 4]
```diff
@@ -172,8 +222,18 @@ defmodule Goth do
...
+  defp start_http_client(func) when is_function(func, 1) do
+    {func, []}
+  end
+
+  defp start_http_client({func, opts}) when is_function(func, 1) do
+    {func, opts}
+  end
+
+  defp start_http_client({module, _} = config) when is_atom(module) do
+    Logger.warn("Setting http_client: {mod, opts} is deprecated in favour of http_client: &fun/1 | {&fun/1, opts}")
```
Comment (wojtekmach) [inline lib/goth.ex:234]:
```suggestion
    Logger.warn("Setting http_client: {mod, opts} is deprecated in favour of http_client: fun | {fun, opts}")
```

File: lib/goth.ex [hunk 5]
```diff
@@ -77,12 +82,51 @@ defmodule Goth do
...
+
+      raise "missing hackney dependency"
+    end
+
+    {:ok, _} = Application.ensure_all_started(:hackney)
+
+    :ok
+  end
+
+  @doc false
```
[the remark this answers is not in the document]
Comment (aleDsz) [reply lib/goth.ex:117]: TIL: didn't know about that

File: lib/goth.ex (hunk 1 above)
Comment (aleDsz) [reply lib/goth.ex:43]: I like this idea, I'll make that change

File: lib/goth.ex (hunk 4 above)
Comment (wojtekmach) [reply lib/goth.ex:234]: nah, let's keep it brief.

File: lib/goth.ex (hunk 1 above)
Comment (aleDsz) [reply lib/goth.ex:43]: Also, added a case when you only use `:hackney` without options

File: lib/goth.ex [hunk 6]
```diff
@@ -77,12 +96,56 @@ defmodule Goth do
...
+      quote do
+        unless Code.ensure_loaded?(:hackney) do
+          Logger.error("""
+          Could not find hackney dependency.
+
+          Please add :hackney to your dependencies:
+
+              {:hackney, "~> 1.17"}
+
+          Or use a different HTTP client. See Goth for more information.
```
Comment (wojtekmach) [inline lib/goth.ex:118]:
```suggestion
          Or use a different HTTP client. See Goth.start_link/1 documentation for more information.
```

File: lib/goth.ex [hunk 7]
```diff
@@ -33,9 +36,25 @@ defmodule Goth do
       that it is tried to be automatically refreshed. Defaults to
       `#{@refresh_before_minutes * 60}` (#{@refresh_before_minutes} minutes).
 
-    * `:http_client` - a `{module, opts}` tuple, where `module` implements the
-      `Goth.HTTPClient` behaviour and `opts` is a keywords list to initialize the client with.
-      Defaults to `{Goth.HTTPClient.Hackney, []}`.
+    * `:http_client` - a `{&fun/1, opts}` tuple or `&fun/1`, where `fun` is a
```
Comment (wojtekmach) [inline lib/goth.ex:39]: please remove this section as it's now a duplicate.

File: lib/goth.ex [hunk 8]
```diff
@@ -33,9 +36,25 @@ defmodule Goth do
...
+
+      * `fun` - same as `{fun, []}`
+
+      * `{fun, opts}` - `fun` must be a 1-arity function that receives a keyword list with fields
+        `:method`, `:url`, `:headers`, and `:body` along with any passed `opts`. The function must return
+        `{:ok, %{status: status, headers: headers, body: body}}` or `{:error, exception}`.
+        Example: `{&HTTPClient.request/1, connect_timeout: 5000}`.
+
+        `fun` can also be an atom `:hackney` to use the built-in [Hackney](http://github.com/benoitc/hackney)-based
+        client.
```
Comment (wojtekmach) [inline lib/goth.ex:55]:
```suggestion
      `fun` can also be an atom `:hackney` to use the built-in [Hackney](http://github.com/benoitc/hackney)-based
      client.
```

File: lib/goth/token.ex [hunk 9]
```diff
@@ -282,6 +279,21 @@ defmodule Goth.Token do
...
+  defp request({mod, _} = config, method, url, headers, body, opts) when is_atom(mod) do
+    Goth.HTTPClient.request(config, method, url, headers, body, opts)
+  end
+
+  defp request({func, initial_state}, method, url, headers, body, options) do
+    request_options = [method: method, url: url, headers: headers, body: body]
+
+    opts =
+      initial_state
+      |> Keyword.merge(options)
```
Comment (wojtekmach) [inline lib/goth/token.ex:291]: Oh, this `options` variable was never used, sorry about that. While at it, do you mind removing it?

File: lib/goth.ex [hunk 10]
```diff
@@ -172,8 +235,26 @@ defmodule Goth do
...
+  defp start_http_client(func) when is_function(func, 1) do
+    {func, []}
+  end
+
+  defp start_http_client({func, opts}) when is_function(func, 1) do
+    {func, opts}
+  end
+
+  defp start_http_client({module, _} = config) when is_atom(module) do
+    Logger.warn("Setting http_client: {mod, opts} is deprecated in favour of http_client: fun | {fun, opts}")
```
Comment (wojtekmach) [inline lib/goth.ex:255]:
```suggestion
    Logger.warn("Setting http_client: mod | {mod, opts} is deprecated in favour of http_client: fun | {fun, opts}")
```

File: lib/goth/token.ex [hunk 11]
```diff
@@ -32,8 +32,8 @@ defmodule Goth.Token do
 
     * `:source` - See "Source" section below.
 
-    * `:http_client` - HTTP client configuration, defaults to using `Goth.HTTPClient.Hackney`.
-      See `Goth.HTTPClient` for more information.
+    * `:http_client` - HTTP client configuration, defaults to using `{&Goth.__hackney__/1, []}`.
+      See `Goth` for more information.
```
Comment (wojtekmach) [inline lib/goth/token.ex:36]: notice Goth.start_links/1 tells users to check out :source option in Goth.Token.fetch. Thus we shouldn't say in Goth.Token.fetch to see Goth.start_link/1 to check :http_client option. We need to pick a module which should give the most information. Let's stick to giving more docs on Goth.Token.

File: lib/goth/token.ex [hunk 12]
```diff
@@ -130,10 +130,7 @@ defmodule Goth.Token do
   @doc since: "1.3.0"
   @spec fetch(map()) :: {:ok, t()} | {:error, Exception.t()}
   def fetch(config) when is_map(config) do
-    config =
-      Map.put_new_lazy(config, :http_client, fn ->
-        Goth.HTTPClient.init({Goth.HTTPClient.Hackney, []})
-      end)
+    config = Map.put_new(config, :http_client, {&Goth.__hackney__/1, []})
```
Comment (wojtekmach) [inline lib/goth/token.ex:133]:
```suggestion
    config = Map.put_new(config, :http_client, {:hackney, []})
```

File: lib/goth/token.ex [hunk 13]
```diff
@@ -157,7 +154,7 @@ defmodule Goth.Token do
     grant_type = "urn:ietf:params:oauth:grant-type:jwt-bearer"
     body = "grant_type=#{grant_type}&assertion=#{jwt}"
 
-    response = Goth.HTTPClient.request(config.http_client, :post, url, headers, body, [])
+    response = request(config.http_client, :post, url, headers, body, [])
```
Comment (wojtekmach) [inline lib/goth/token.ex:157]: if we do this:

```suggestion
    response = request(config.http_client, method: :post, url: url, headers: headers, body: body)
```

then I think our `request/2` is gonna be super simple:

```elixir
defp request({fun, extra_options}, options) do
  fun.(options ++ extra_options)
end
```

Btw, nitpick, please use the word `fun` instead of `func` as it is more common for this type of a thing.

Comment (aleDsz) [reply lib/goth/token.ex:157]: I would make a joke about that, but probably wouldn't become fun to read. 😹

File: lib/goth/token.ex (hunk 11 above)
Comment (aleDsz) [reply lib/goth/token.ex:36]: Sure, I'll add more detailed docs + examples. WDYT?

Comment (wojtekmach) [reply lib/goth/token.ex:36]: sounds good

File: lib/goth/token.ex [hunk 14]
```diff
@@ -126,14 +170,24 @@ defmodule Goth.Token do
...
   for more information on metadata server.
+
+
+  #### Using a custom HTTP Client:
+
+      iex> http_request = fn options ->
+      ...>   req = Req.build(options[:method], options[:url], options)
+      ...>   req = Req.put_default_steps(req)
+      ...>   Req.run(req)
+      ...> end
```
Comment (wojtekmach) [inline lib/goth/token.ex:181]: the idea is it is gonna be simply: `http_client: &Req.request/1`. ;) Don't worry about it though, I'll update the docs on master.
